pipeline {
    agent any
    
    tools {
       jdk "javaJdk"
       }
    stages {
        stage('Build') {
            steps {
            echo 'Hello user'
            dir ('JenkinsSample'){
            bat 'ant build'
            }
        }
        }
        stage('Jarfile'){
        	steps{
	        	echo 'jar file generated'
	        	dir ('JenkinsSample'){
	        	 	bat 'ant generatejarfile'
                }
             }
        }
        
     }
}