pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
            echo 'Hello user' 
            }
        }
        stage('Test'){
        	steps{
        	echo 'Testing..'
        	}
        }
        stage('Deploy'){
        	steps{
        	echo 'Deploying..'
        	}
        }
        stage('Jarfile'){
        	steps{
	        	echo 'jar file generated'
	        	 dir ('build') {
	        	 	filename 'build.xml'
	        	    bat 'ant build.xml'
                }
        	}
        }
         stage('Example Test') {
            agent { docker 'openjdk:8-jre' } 
            steps {
                echo 'Hello, JDK'
                bat 'java -version'
            }
        }
        
     }
}